import { Technique, CORES } from './technique';
export const TECHNIQUES: Technique[] = [

    { id: '-Anticipation Parade', cx: -30, cy: -30, radio: '30', fillId: 'url(#ACCOMPLISHMENT)', fillIdOri: 'url(#ACCOMPLISHMENT)', class: 'bounceInUp', type: 'Accomplishment', done: false },
    { id: '-Appointment Dynamics', cx: -30, cy: -30, radio: '30', fillId: 'url(#SCARCITY)', fillIdOri: 'url(#SCARCITY)', class: 'bounceInLeft', type: 'Scarcity', done: false },
    { id: '-Aura Effect', cx: -30, cy: -30, radio: '30', fillId: 'url(#ACCOMPLISHMENT)', fillIdOri: 'url(#ACCOMPLISHMENT)', class: 'bounceIn', type: 'Accomplishment', done: false },
    { id: '-Badges (Achievement Symbols)', cx: -30, cy: -30, radio: '30', fillId: 'url(#ACCOMPLISHMENT)', fillIdOri: 'url(#ACCOMPLISHMENT)', class: 'bounceInDown', type: 'Accomplishment', done: false },
    { id: '-Beginners Luck', cx: -30, cy: -30, radio: '30', fillId: 'url(#MEANING)', fillIdOri: 'url(#MEANING)', class: 'bounceInDown', type: 'Meaning', done: false },
    { id: '-Boosters', cx: -30, cy: -30, radio: '30', fillId: 'url(#EMPOWERMENT)', fillIdOri: 'url(#EMPOWERMENT)', class: 'bounceInLeft', type: 'Empowerment', done: false },
    { id: '-Build From Scratch', cx: -30, cy: -30, radio: '30', fillId: 'url(#OWNERSHIP)', fillIdOri: 'url(#OWNERSHIP)', class: 'bounceIn', type: 'Ownership', done: false },
    { id: '-CountDown Timer', cx: -30, cy: -30, radio: '30', fillId: 'url(#SCARCITY)', fillIdOri: 'url(#SCARCITY)', class: 'bounceInRight', type: 'Scarcity', done: false },
    { id: '-Crowning', cx: -30, cy: -30, radio: '30', fillId: 'url(#ACCOMPLISHMENT)', fillIdOri: 'url(#ACCOMPLISHMENT)', class: 'bounceInRight', type: 'Accomplishment', done: false },
    { id: '-Desert Oasis', cx: -30, cy: -30, radio: '30', fillId: 'url(#ACCOMPLISHMENT)', fillIdOri: 'url(#ACCOMPLISHMENT)', class: 'bounceInDown', type: 'Accomplishment', done: false },
    { id: '-Destiny Child', cx: -30, cy: -30, radio: '30', fillId: 'url(#MEANING)', fillIdOri: 'url(#MEANING)', class: 'bounceInRight', type: 'Meaning', done: false },
    { id: '-Fixed Action Rewards (Earned Lunch)', cx: -30, cy: -30, radio: '30', fillId: 'url(#ACCOMPLISHMENT)', fillIdOri: 'url(#ACCOMPLISHMENT)', class: 'bounceInLeft', type: 'Accomplishment', done: false },
    { id: '-High Five', cx: -30, cy: -30, radio: '30', fillId: 'url(#ACCOMPLISHMENT)', fillIdOri: 'url(#ACCOMPLISHMENT)', class: 'bounceInLeft', type: 'Accomplishment', done: false },
    { id: '-Humanity Hero', cx: -30, cy: -30, radio: '30', fillId: 'url(#MEANING)', fillIdOri: 'url(#MEANING)', class: 'bounceInUp', type: 'Meaning', done: false },
    { id: '-Leaderboard', cx: -30, cy: -30, radio: '30', fillId: 'url(#ACCOMPLISHMENT)', fillIdOri: 'url(#ACCOMPLISHMENT)', class: 'bounceInRight', type: 'Accomplishment', done: false },
    { id: '-Monitor Attachment', cx: -30, cy: -30, radio: '30', fillId: 'url(#OWNERSHIP)', fillIdOri: 'url(#OWNERSHIP)', class: 'bounceInDown', type: 'Ownership', done: false },
    { id: '-Poison Pickers', cx: -30, cy: -30, radio: '30', fillId: 'url(#EMPOWERMENT)', fillIdOri: 'url(#EMPOWERMENT)', class: 'bounceIn', type: 'Empowerment', done: false },
    { id: '-Progress Bar', cx: -30, cy: -30, radio: '30', fillId: 'url(#ACCOMPLISHMENT)', fillIdOri: 'url(#ACCOMPLISHMENT)', class: 'bounceInUp', type: 'Accomplishment', done: false },
    { id: '-Protection', cx: -30, cy: -30, radio: '30', fillId: 'url(#OWNERSHIP)', fillIdOri: 'url(#OWNERSHIP)', class: 'bounceInUp', type: 'Ownership', done: false },
    { id: '-Quest Lists', cx: -30, cy: -30, radio: '30', fillId: 'url(#ACCOMPLISHMENT)', fillIdOri: 'url(#ACCOMPLISHMENT)', class: 'bounceIn', type: 'Accomplishment', done: false },
    { id: '-Random Rewards', cx: -30, cy: -30, radio: '30', fillId: 'url(#UNPREDICTABILITY)', fillIdOri: 'url(#UNPREDICTABILITY)', class: 'bounceIn', type: 'Unpredictability', done: false },
    { id: '-Scarlet Letter', cx: -30, cy: -30, radio: '30', fillId: 'url(#AVOIDANCE)', fillIdOri: 'url(#AVOIDANCE)', class: 'bounceIn', type: 'Avoidance', done: false },
    { id: '-Social Proud', cx: -30, cy: -30, radio: '30', fillId: 'url(#SOCIAL_INFLUENCE)', fillIdOri: 'url(#SOCIAL_INFLUENCE)', class: 'bounceIn', type: 'Social Influence', done: false },
    { id: '-Status Points', cx: -30, cy: -30, radio: '30', fillId: 'url(#ACCOMPLISHMENT)', fillIdOri: 'url(#ACCOMPLISHMENT)', class: 'bounceIn', type: 'Accomplishment', done: false },
    { id: '-Status Quo Sloth', cx: -30, cy: -30, radio: '30', fillId: 'url(#AVOIDANCE)', fillIdOri: 'url(#AVOIDANCE)', class: 'bounceInUp', type: 'Avoidance', done: false },
    { id: '-Step-by-Step Overlay Tutorial', cx: -30, cy: -30, radio: '30', fillId: 'url(#ACCOMPLISHMENT)', fillIdOri: 'url(#ACCOMPLISHMENT)', class: 'bounceInDown', type: 'Accomplishment', done: false },
    { id: '-Sunk Cost Prison', cx: -30, cy: -30, radio: '30', fillId: 'url(#AVOIDANCE)', fillIdOri: 'url(#AVOIDANCE)', class: 'bounceIn', type: 'Avoidance', done: false },
    { id: '-Torture Breaks', cx: -30, cy: -30, radio: '30', fillId: 'url(#SCARCITY)', fillIdOri: 'url(#SCARCITY)', class: 'bounceInUp', type: 'Scarcity', done: false },
    { id: '-Virtual Goods', cx: -30, cy: -30, radio: '30', fillId: 'url(#OWNERSHIP)', fillIdOri: 'url(#OWNERSHIP)', class: 'bounceInUp', type: 'Ownership', done: false },

];