import { Technique, CORES } from './technique';
export const TECHNIQUES: Technique[] = [

    { id: '-Status Points', cx: -30, cy: -30, radio: '30', fillId: 'url(#ACCOMPLISHMENT)', fillIdOri: 'url(#ACCOMPLISHMENT)', class: 'bounceIn', type: 'Accomplishment', done: false },
    { id: '-Badges (Achievement Symbols)', cx: -30, cy: -30, radio: '30', fillId: 'url(#ACCOMPLISHMENT)', fillIdOri: 'url(#ACCOMPLISHMENT)', class: 'bounceInDown', type: 'Accomplishment', done: false },
    { id: '-Fixed Action Rewards (Earned Lunch)', cx: -30, cy: -30, radio: '30', fillId: 'url(#ACCOMPLISHMENT)', fillIdOri: 'url(#ACCOMPLISHMENT)', class: 'bounceInLeft', type: 'Accomplishment', done: false },
    { id: '-Leaderboard', cx: -30, cy: -30, radio: '30', fillId: 'url(#ACCOMPLISHMENT)', fillIdOri: 'url(#ACCOMPLISHMENT)', class: 'bounceInRight', type: 'Accomplishment', done: false },
    { id: '-Progress Bar', cx: -30, cy: -30, radio: '30', fillId: 'url(#ACCOMPLISHMENT)', fillIdOri: 'url(#ACCOMPLISHMENT)', class: 'bounceInUp', type: 'Accomplishment', done: false },
    { id: '-Quest Lists', cx: -30, cy: -30, radio: '30', fillId: 'url(#ACCOMPLISHMENT)', fillIdOri: 'url(#ACCOMPLISHMENT)', class: 'bounceIn', type: 'Accomplishment', done: false },
    { id: '-Desert Oasis', cx: -30, cy: -30, radio: '30', fillId: 'url(#ACCOMPLISHMENT)', fillIdOri: 'url(#ACCOMPLISHMENT)', class: 'bounceInDown', type: 'Accomplishment', done: false },
    { id: '-High Five', cx: -30, cy: -30, radio: '30', fillId: 'url(#ACCOMPLISHMENT)', fillIdOri: 'url(#ACCOMPLISHMENT)', class: 'bounceInLeft', type: 'Accomplishment', done: false },
    { id: '-Crowning', cx: -30, cy: -30, radio: '30', fillId: 'url(#ACCOMPLISHMENT)', fillIdOri: 'url(#ACCOMPLISHMENT)', class: 'bounceInRight', type: 'Accomplishment', done: false },
    { id: '-Anticipation Parade', cx: -30, cy: -30, radio: '30', fillId: 'url(#ACCOMPLISHMENT)', fillIdOri: 'url(#ACCOMPLISHMENT)', class: 'bounceInUp', type: 'Accomplishment', done: false },
    { id: '-Aura Effect', cx: -30, cy: -30, radio: '30', fillId: 'url(#ACCOMPLISHMENT)', fillIdOri: 'url(#ACCOMPLISHMENT)', class: 'bounceIn', type: 'Accomplishment', done: false },
    { id: '-Step-by-Step Overlay Tutorial', cx: -30, cy: -30, radio: '30', fillId: 'url(#ACCOMPLISHMENT)', fillIdOri: 'url(#ACCOMPLISHMENT)', class: 'bounceInDown', type: 'Accomplishment', done: false },
    { id: '-Boss Fights', cx: -30, cy: -30, radio: '30', fillId: 'url(#ACCOMPLISHMENT)', fillIdOri: 'url(#ACCOMPLISHMENT)', class: 'bounceInLeft', type: 'Accomplishment', done: false },
    { id: '-Exchangeable Points', cx: -30, cy: -30, radio: '30', fillId: 'url(#OWNERSHIP)', fillIdOri: 'url(#OWNERSHIP)', class: 'bounceInRight', type: 'Ownership', done: false },
    { id: '-Virtual Goods', cx: -30, cy: -30, radio: '30', fillId: 'url(#OWNERSHIP)', fillIdOri: 'url(#OWNERSHIP)', class: 'bounceInUp', type: 'Ownership', done: false },
    { id: '-Build from Scratch', cx: -30, cy: -30, radio: '30', fillId: 'url(#OWNERSHIP)', fillIdOri: 'url(#OWNERSHIP)', class: 'bounceIn', type: 'Ownership', done: false },
    { id: '-Alfred Effect', cx: -30, cy: -30, radio: '30', fillId: 'url(#OWNERSHIP)', fillIdOri: 'url(#OWNERSHIP)', class: 'bounceInDown', type: 'Ownership', done: false },
    { id: '-Collection Sets', cx: -30, cy: -30, radio: '30', fillId: 'url(#OWNERSHIP)', fillIdOri: 'url(#OWNERSHIP)', class: 'bounceInLeft', type: 'Ownership', done: false },
    { id: '-Avatar', cx: -30, cy: -30, radio: '30', fillId: 'url(#OWNERSHIP)', fillIdOri: 'url(#OWNERSHIP)', class: 'bounceInRight', type: 'Ownership', done: false },
    { id: '-Protection', cx: -30, cy: -30, radio: '30', fillId: 'url(#OWNERSHIP)', fillIdOri: 'url(#OWNERSHIP)', class: 'bounceInUp', type: 'Ownership', done: false },
    { id: '-Recruiter Burden', cx: -30, cy: -30, radio: '30', fillId: 'url(#OWNERSHIP)', fillIdOri: 'url(#OWNERSHIP)', class: 'bounceIn', type: 'Ownership', done: false },
    { id: '-Monitor Attachment', cx: -30, cy: -30, radio: '30', fillId: 'url(#OWNERSHIP)', fillIdOri: 'url(#OWNERSHIP)', class: 'bounceInDown', type: 'Ownership', done: false },
    { id: '-Appointment Dynamics', cx: -30, cy: -30, radio: '30', fillId: 'url(#SCARCITY)', fillIdOri: 'url(#SCARCITY)', class: 'bounceInLeft', type: 'Scarcity', done: false },
    { id: '-Magnetic Caps', cx: -30, cy: -30, radio: '30', fillId: 'url(#SCARCITY)', fillIdOri: 'url(#SCARCITY)', class: 'bounceInRight', type: 'Scarcity', done: false },
    { id: '-Dangling', cx: -30, cy: -30, radio: '30', fillId: 'url(#SCARCITY)', fillIdOri: 'url(#SCARCITY)', class: 'bounceInUp', type: 'Scarcity', done: false },
    { id: '-Prize Pacing', cx: -30, cy: -30, radio: '30', fillId: 'url(#SCARCITY)', fillIdOri: 'url(#SCARCITY)', class: 'bounceIn', type: 'Scarcity', done: false },
    { id: '-Options Pacing', cx: -30, cy: -30, radio: '30', fillId: 'url(#SCARCITY)', fillIdOri: 'url(#SCARCITY)', class: 'bounceInDown', type: 'Scarcity', done: false },
    { id: '-Last Mile Drive', cx: -30, cy: -30, radio: '30', fillId: 'url(#SCARCITY)', fillIdOri: 'url(#SCARCITY)', class: 'bounceInLeft', type: 'Scarcity', done: false },
    { id: '-Count Down Timer', cx: -30, cy: -30, radio: '30', fillId: 'url(#SCARCITY)', fillIdOri: 'url(#SCARCITY)', class: 'bounceInRight', type: 'Scarcity', done: false },
    { id: '-Torture Breaks', cx: -30, cy: -30, radio: '30', fillId: 'url(#SCARCITY)', fillIdOri: 'url(#SCARCITY)', class: 'bounceInUp', type: 'Scarcity', done: false },
    { id: '-Moats', cx: -30, cy: -30, radio: '30', fillId: 'url(#SCARCITY)', fillIdOri: 'url(#SCARCITY)', class: 'bounceIn', type: 'Scarcity', done: false },
    { id: '-The Big Burn', cx: -30, cy: -30, radio: '30', fillId: 'url(#SCARCITY)', fillIdOri: 'url(#SCARCITY)', class: 'bounceInDown', type: 'Scarcity', done: false },
    { id: '-Narrative', cx: -30, cy: -30, radio: '30', fillId: 'url(#MEANING)', fillIdOri: 'url(#MEANING)', class: 'bounceInLeft', type: 'Meaning', done: false },
    { id: '-Elitism', cx: -30, cy: -30, radio: '30', fillId: 'url(#MEANING)', fillIdOri: 'url(#MEANING)', class: 'bounceInRight', type: 'Meaning', done: false },
    { id: '-Humanity Hero', cx: -30, cy: -30, radio: '30', fillId: 'url(#MEANING)', fillIdOri: 'url(#MEANING)', class: 'bounceInUp', type: 'Meaning', done: false },
    { id: '-Revealed Heart', cx: -30, cy: -30, radio: '30', fillId: 'url(#MEANING)', fillIdOri: 'url(#MEANING)', class: 'bounceIn', type: 'Meaning', done: false },
    { id: '-Beginners Luck', cx: -30, cy: -30, radio: '30', fillId: 'url(#MEANING)', fillIdOri: 'url(#MEANING)', class: 'bounceInDown', type: 'Meaning', done: false },
    { id: '-Free Lunch', cx: -30, cy: -30, radio: '30', fillId: 'url(#MEANING)', fillIdOri: 'url(#MEANING)', class: 'bounceInLeft', type: 'Meaning', done: false },
    { id: '-Destiny Child', cx: -30, cy: -30, radio: '30', fillId: 'url(#MEANING)', fillIdOri: 'url(#MEANING)', class: 'bounceInRight', type: 'Meaning', done: false },
    { id: '-Creationist', cx: -30, cy: -30, radio: '30', fillId: 'url(#MEANING)', fillIdOri: 'url(#MEANING)', class: 'bounceInUp', type: 'Meaning', done: false },
    { id: '-Sunk Cost Prison', cx: -30, cy: -30, radio: '30', fillId: 'url(#AVOIDANCE)', fillIdOri: 'url(#AVOIDANCE)', class: 'bounceIn', type: 'Avoidance', done: false },
    { id: '-Progress Loss', cx: -30, cy: -30, radio: '30', fillId: 'url(#AVOIDANCE)', fillIdOri: 'url(#AVOIDANCE)', class: 'bounceInDown', type: 'Avoidance', done: false },
    { id: '-Rightful Heritage', cx: -30, cy: -30, radio: '30', fillId: 'url(#AVOIDANCE)', fillIdOri: 'url(#AVOIDANCE)', class: 'bounceInLeft', type: 'Avoidance', done: false },
    { id: '-Evanescence Opportunity', cx: -30, cy: -30, radio: '30', fillId: 'url(#AVOIDANCE)', fillIdOri: 'url(#AVOIDANCE)', class: 'bounceInRight', type: 'Avoidance', done: false },
    { id: '-Status Quo Sloth', cx: -30, cy: -30, radio: '30', fillId: 'url(#AVOIDANCE)', fillIdOri: 'url(#AVOIDANCE)', class: 'bounceInUp', type: 'Avoidance', done: false },
    { id: '-Scarlet Letter', cx: -30, cy: -30, radio: '30', fillId: 'url(#AVOIDANCE)', fillIdOri: 'url(#AVOIDANCE)', class: 'bounceIn', type: 'Avoidance', done: false },
    { id: '-Visual Grave', cx: -30, cy: -30, radio: '30', fillId: 'url(#AVOIDANCE)', fillIdOri: 'url(#AVOIDANCE)', class: 'bounceInDown', type: 'Avoidance', done: false },
    { id: '-FOMO Punch', cx: -30, cy: -30, radio: '30', fillId: 'url(#AVOIDANCE)', fillIdOri: 'url(#AVOIDANCE)', class: 'bounceInLeft', type: 'Avoidance', done: false },
    { id: '-Milestone Unlocks', cx: -30, cy: -30, radio: '30', fillId: 'url(#EMPOWERMENT)', fillIdOri: 'url(#EMPOWERMENT)', class: 'bounceInRight', type: 'Empowerment', done: false },
    { id: '-Real-Time Control', cx: -30, cy: -30, radio: '30', fillId: 'url(#EMPOWERMENT)', fillIdOri: 'url(#EMPOWERMENT)', class: 'bounceInUp', type: 'Empowerment', done: false },
    { id: '-Evergreen Combos', cx: -30, cy: -30, radio: '30', fillId: 'url(#EMPOWERMENT)', fillIdOri: 'url(#EMPOWERMENT)', class: 'bounceIn', type: 'Empowerment', done: false },
    { id: '-Instant feedback', cx: -30, cy: -30, radio: '30', fillId: 'url(#EMPOWERMENT)', fillIdOri: 'url(#EMPOWERMENT)', class: 'bounceInDown', type: 'Empowerment', done: false },
    { id: '-Boosters', cx: -30, cy: -30, radio: '30', fillId: 'url(#EMPOWERMENT)', fillIdOri: 'url(#EMPOWERMENT)', class: 'bounceInLeft', type: 'Empowerment', done: false },
    { id: '-Blank Fills', cx: -30, cy: -30, radio: '30', fillId: 'url(#EMPOWERMENT)', fillIdOri: 'url(#EMPOWERMENT)', class: 'bounceInRight', type: 'Empowerment', done: false },
    { id: '-Plant Pickers', cx: -30, cy: -30, radio: '30', fillId: 'url(#EMPOWERMENT)', fillIdOri: 'url(#EMPOWERMENT)', class: 'bounceInUp', type: 'Empowerment', done: false },
    { id: '-Poison Pickers', cx: -30, cy: -30, radio: '30', fillId: 'url(#EMPOWERMENT)', fillIdOri: 'url(#EMPOWERMENT)', class: 'bounceIn', type: 'Empowerment', done: false },
    { id: '-Friending', cx: -30, cy: -30, radio: '30', fillId: 'url(#SOCIAL_INFLUENCE)', fillIdOri: 'url(#SOCIAL_INFLUENCE)', class: 'bounceInDown', type: 'Social Influence', done: false },
    { id: '-Social Treasure/Gifting', cx: -30, cy: -30, radio: '30', fillId: 'url(#SOCIAL_INFLUENCE)', fillIdOri: 'url(#SOCIAL_INFLUENCE)', class: 'bounceInLeft', type: 'Social Influence', done: false },
    { id: '-SeeSaw Bump', cx: -30, cy: -30, radio: '30', fillId: 'url(#SOCIAL_INFLUENCE)', fillIdOri: 'url(#SOCIAL_INFLUENCE)', class: 'bounceInRight', type: 'Social Influence', done: false },
    { id: '-Group Quests', cx: -30, cy: -30, radio: '30', fillId: 'url(#SOCIAL_INFLUENCE)', fillIdOri: 'url(#SOCIAL_INFLUENCE)', class: 'bounceInUp', type: 'Social Influence', done: false },
    { id: '-Tout Flags', cx: -30, cy: -30, radio: '30', fillId: 'url(#SOCIAL_INFLUENCE)', fillIdOri: 'url(#SOCIAL_INFLUENCE)', class: 'bounceIn', type: 'Social Influence', done: false },
    { id: '-Brag Button', cx: -30, cy: -30, radio: '30', fillId: 'url(#SOCIAL_INFLUENCE)', fillIdOri: 'url(#SOCIAL_INFLUENCE)', class: 'bounceInDown', type: 'Social Influence', done: false },
    { id: '-Water Cooler', cx: -30, cy: -30, radio: '30', fillId: 'url(#SOCIAL_INFLUENCE)', fillIdOri: 'url(#SOCIAL_INFLUENCE)', class: 'bounceInLeft', type: 'Social Influence', done: false },
    { id: '-Conformity Anchors', cx: -30, cy: -30, radio: '30', fillId: 'url(#SOCIAL_INFLUENCE)', fillIdOri: 'url(#SOCIAL_INFLUENCE)', class: 'bounceInRight', type: 'Social Influence', done: false },
    { id: '-Mentorship', cx: -30, cy: -30, radio: '30', fillId: 'url(#SOCIAL_INFLUENCE)', fillIdOri: 'url(#SOCIAL_INFLUENCE)', class: 'bounceInUp', type: 'Social Influence', done: false },
    { id: '-Social Prod', cx: -30, cy: -30, radio: '30', fillId: 'url(#SOCIAL_INFLUENCE)', fillIdOri: 'url(#SOCIAL_INFLUENCE)', class: 'bounceIn', type: 'Social Influence', done: false },
    { id: '-Glowing Choice', cx: -30, cy: -30, radio: '30', fillId: 'url(#UNPREDICTABILITY)', fillIdOri: 'url(#UNPREDICTABILITY)', class: 'bounceInDown', type: 'Unpredictability', done: false },
    { id: '-MiniQuests', cx: -30, cy: -30, radio: '30', fillId: 'url(#UNPREDICTABILITY)', fillIdOri: 'url(#UNPREDICTABILITY)', class: 'bounceInLeft', type: 'Unpredictability', done: false },
    { id: '-Visual Storytelling', cx: -30, cy: -30, radio: '30', fillId: 'url(#UNPREDICTABILITY)', fillIdOri: 'url(#UNPREDICTABILITY)', class: 'bounceInRight', type: 'Unpredictability', done: false },
    { id: '-Easter Eggs', cx: -30, cy: -30, radio: '30', fillId: 'url(#UNPREDICTABILITY)', fillIdOri: 'url(#UNPREDICTABILITY)', class: 'bounceInUp', type: 'Unpredictability', done: false },
    { id: '-Random Rewards', cx: -30, cy: -30, radio: '30', fillId: 'url(#UNPREDICTABILITY)', fillIdOri: 'url(#UNPREDICTABILITY)', class: 'bounceIn', type: 'Unpredictability', done: false },
    { id: '-Obvious Wonder', cx: -30, cy: -30, radio: '30', fillId: 'url(#UNPREDICTABILITY)', fillIdOri: 'url(#UNPREDICTABILITY)', class: 'bounceInDown', type: 'Unpredictability', done: false },
    { id: '-Rolling Rewards', cx: -30, cy: -30, radio: '30', fillId: 'url(#UNPREDICTABILITY)', fillIdOri: 'url(#UNPREDICTABILITY)', class: 'bounceInLeft', type: 'Unpredictability', done: false },
    { id: '-Evolved UI', cx: -30, cy: -30, radio: '30', fillId: 'url(#UNPREDICTABILITY)', fillIdOri: 'url(#UNPREDICTABILITY)', class: 'bounceInRight', type: 'Unpredictability', done: false },
    { id: '-Sudden Rewards', cx: -30, cy: -30, radio: '30', fillId: 'url(#UNPREDICTABILITY)', fillIdOri: 'url(#UNPREDICTABILITY)', class: 'bounceInUp', type: 'Unpredictability', done: false },
    { id: '-Oracle Effect', cx: -30, cy: -30, radio: '30', fillId: 'url(#UNPREDICTABILITY)', fillIdOri: 'url(#UNPREDICTABILITY)', class: 'bounceIn', type: 'Unpredictability', done: false },


];